# change it accordingly
# also change the load_default_config flag in train and classify respectively


model:
  script_path: ../project/model.py

utils:
  script_path: ../project/utils.py

optimizer:
  type: adam
  learning_rate: 0.001

scheduler:
  type: step
  step_size: 10
  gamma: 0.1

training:
  num_epochs: 50
  batch_size: 32
  save_dir: models/
  log_dir: logs/
