
optimizer:
  type: adam
  learning_rate: 0.001

scheduler:
  type: step
  step_size: 10
  gamma: 0.1

training:
  epochs: 1
  batch_size: 32
  save_dir: models/simple_img_clf_weights.pth
  log_dir: logs
  lr: 0.0001

pre_processing:
  resize_height: 300
  resize_width: 500
  mean: 4.8795
  std: 0.5321
